In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
n=arr[arr%2==1]
print(n)

[1 3 5 7 9]


In [7]:
#reshape array
import numpy as np
arr= np.arange(10)
x=arr.reshape(2,-1)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
#to reverse row of 2d array
import numpy as np
arr=np.arange(9)
n=arr[::-1]
print(n)

[8 7 6 5 4 3 2 1 0]


In [5]:
rand_arr=np.random.uniform(5,10,size=(5,3))
print(rand_arr)

[[7.21371184 7.780798   9.14537802]
 [6.70790331 5.31641371 5.92436691]
 [5.34857701 9.24738056 9.77686661]
 [7.77156716 7.59695807 9.89394619]
 [6.32419665 9.17031813 7.11364469]]
